### ISSUE TITLE
Game Tree abstract structure

### ISSUE THREAD

**Issue by a-batts** [a-batts/cypher-vii#14]
Create a Game Tree abstract structure to power the choose-your-own-adventure functionality 

- [x] Game Tree parent class
- [x] Tree Node child class
- [x] Handle offering different prompts based on user's skill levels 
- [x] Read choices from json structure and build tree
- [x] Run prompt class while navigating down tree
- [x] Runnable from main

**Comment by jasonycin** [comment]
Can you expand on how you'd like choices read? What's the input, the expected return, etc.?
